### ISSUE TITLE
Make ASPNET 5 compatible

### ISSUE THREAD

**Issue by 304NotModified** [NLog/NLog.Web#29]
This library isn't working with ASP.NET 5. The `HttpContext.Current` is not there:

http://stackoverflow.com/questions/31243068/httpcontext-current-in-asp-net-vnext

Too bad, I think we need a new package for that? (e.g. NLog.Web.Aspnet5) - as I didn't found a way to detect ASP.NET5

**Comment by epignosisx** [comment]
A new package is going to be needed. Everything has changed for ASP.NET 5 or after the latest rename: AspNetCore.

**Comment by 304NotModified** [comment]
Hey @epignosisx 

Do you now the difference between dnx451 and net451? Do you know if you can run ASP.NET 5 on net451?

**Comment by epignosisx** [comment]
I've trying to keep up with .NET Core and AspNetCore but I find things confusing and they will continue to change. My understanding is that dnx451 and dnxcore50 is what you target for applications, not class libraries. Class libraries target net451 (full .NET Framework) and dotnet5.x (new portable abstraction moniker soon to be renamed to netstandard1.x by RC2). Since NLog is a class library the latter is what needs to be used.

Frankly, things are still changing, the VS tooling is not ready yet to help developers with the new project system and there is little documentation. Hopefully things will be more stable after RC2 is released. 

Sources
https://github.com/aspnet/MusicStore/blob/dev/src/MusicStore/project.json (Sample app project.config)
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Abstractions/project.json (Sample class library project.config)
https://github.com/aspnet/Announcements/issues/98 (Announcement of new DNX monikers for class libraries and application, however as previously said the names will change again)
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md (NET Standard Platform documentation)

**Comment by 304NotModified** [comment]
Thanks @epignosisx 

If I cannot target DNX, then I do need a new package indeed. Because I was thinking.

- net35 -> ASP.NET 4
- dnx451 -> ASP.NET 5
- dnxcore50 (dotnet5.x) -> ASP.NET 5

**Comment by sirentek** [comment]
Hi,

After some dependency issues, I had NLog worked on AspNetCore using a Windows machine.
I am sure it will work on linux too.

I did nothing special, just used my own repo and initialized NLogManager with the Nlog.config file.        I used "NLog": "4.4.0-alpha1"

As I understand, we don't need a new nugget package for AspNetCore for *now*

our new toy rocks :+1:

**Comment by 304NotModified** [comment]
Hi @sirentek 

Did you tried also [NLog.Web.ASPNET5](https://www.nuget.org/packages/NLog.Web.ASPNET5/)? That's the new package special for ASPNET5 (as replacement of  [NLog.Web](https://www.nuget.org/packages/NLog.Web/)). I'm curious what your experiences are. 

You still probable need [NLog.Extensions.Logging](https://www.nuget.org/packages/NLog.Extensions.Logging/) and NLog 4.4.0-alpha1

**Comment by sirentek** [comment]
No, I haven't used NLog.Web.ASPNET5. lt should work because there is not a big change in razor engine as I know.

**Comment by 304NotModified** [comment]
Well there are a lot of breaking changes between ASP.NET4 and 5, and so the new package.

**Comment by 304NotModified** [comment]
anyway, thanks for the feedback :)
