### ISSUE TITLE
No way to use LogFactory with AspNet.Core

### ISSUE THREAD

**Issue by ilya-spv** [NLog/NLog.Web#541]
**Type** (choose one):

- Feature request

**NLog version**:  4.7

**NLog.Web/NLog.Web.AspNetCore version**: 4.9.1

**NLog.Extensions.Logging version**: 1.6.2

**Platform**: .NET Core 3

NLog 4.7 comes with new Setup methods combined in LogFactory to make things easier to configure if I understood it correctly. I have tried to use this feature with Asp.NetCore, but I did not figure out how and it seems impossible.

I have gone a bit though code and in registering a provider have found this:

```
private static NLogLoggerProvider CreateNLogLoggerProvider(
      IServiceProvider serviceProvider,
      IConfiguration configuration,
      NLogAspNetCoreOptions options)
    {
      return AspNetExtensions.CreateNLogLoggerProvider(serviceProvider, configuration, options, (LogFactory) null);
    }
```

It seems that though the option exists in code it is not exposed and hardcoded to null. It would be nice to have this possibility via AspNet.Core.

I have used: `UseNLog()` extension method.

It might it's already being implemented in this [commit](https://github.com/NLog/NLog.Extensions.Logging/commit/4db9fc37d8bf3a9c413220a4a65cee2ee670cd35)?

P.S. Not sure it's required anymore as it's possible to use Setup methods directly on LogManager.

**Comment by snakefoot** [comment]
Yes NLog 4.7 has been released but changes has not been applied to NLog.Extensions.Logging and NLog.Web.AspNetCore.

I have made the following PRs to improve the support for `LogManager.Setup()`. You can see small code-examples also:

https://github.com/NLog/NLog.Web/pull/540
https://github.com/NLog/NLog.Extensions.Logging/pull/412
https://github.com/NLog/NLog/pull/3871

Any input you might have is very welcome.

**Comment by ilya-spv** [comment]
I am not quite sure in how LogManager relate to LogFactory, but I was thinking that e.g. `UseNLog()` could have got a factory parameter to send in. Then it would be possible to use other LogFactories other places without relying on LogManager.

I don't really need this myself and will just use LogManager to do the setup, but since LogFactory is becoming a thing now it might be a good idea to allow it for aspnet.core registration?

**Comment by snakefoot** [comment]
The LogManager is the static singleton instance of LogFactory. Most people use this, because it is easier. The LogFactory have always been in NLog, and is not something new. I'm just trying to improve the support for having multiple isolated LogFactory-instances for ex. ServiceFabric (multiple isolated services running in the same process, thus shared state with static singleton is a no-go)

Here is an example of how to build an isolated LogFactory using the factory-method:

https://github.com/NLog/NLog.Extensions.Logging/issues/406#issuecomment-599762570

Alternative solution where one uses an isolated LogFactory by providing the LoggingConfiguration:

https://github.com/NLog/NLog.Extensions.Logging/issues/406#issuecomment-599786612

**Comment by ilya-spv** [comment]
From your example it looks it is already possible to achieve. I was just using `IHostBuilder` extension but is configured in Services extensions instead, so it's all already there :)

Hope you guys release a version of NLog.Web.AspNetCore that references NLog 4.7 soon :)

Thanks for the great work you are doing!

**Comment by snakefoot** [comment]
Happy to help, and glad you found what you needed :)
